### ISSUE TITLE
Wiki Pages

### ISSUE THREAD

**Issue by xnanodax** [archhere/peginterest#1]
# Wiki Page Home

- [x] Is the first page you see upon entering the wiki
- [x] Contains a welcome message
- [x] Contains a link/placeholder for a link to the live page
- [x] All links in the right sidebar should contain each wiki page and link to the correct page
- [x] Correctly formatted
    - [x] each wiki page is listed in bullet points
    - [x] all links route the correct page

## Comments:

---

# MVP List

- [x] Should have 7 MVPs.
    - [x] 3 of those are User Auth, Heroku, and Production README.
    - [x] The other 4 are from the [MVP List](https://github.com/appacademy/curriculum/blob/master/full-stack-project/proposal/mvp-list.md) or they have clarified them with you
- [x] Contains a description sentence of the app
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each MVP
- [x] Each App specific MVP needs the following bullet points are added:
    + Adequate styling
    + Smooth, bug-free navigation
    + Seeded with info to demonstrate this feature

- [x] Correctly formatted
    - [x] MVPs are listed in an ordered list
    - [x] Each MVP is broken down into bullet points

## Comments:

---

# Database Schema
- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null
    - [x] unique
    - [x] indexed
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made

- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are `back_ticked`
    - [x] the table header column names are bolded
    - [ ] columns names are lowercased and snaked_cased and `back_ticked`
## Comments:

---

# Routes

- [x] Routes accurately reflect MVPs and Component Hierarchy
- [ ] Covers the frontend functionality of the site through routes that match to the wireframes
- [x] Contains the following sections: HTML, API Endpoints(Backend), and Frontend Routes
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint bc that info comes through the post show
- [x] Correctly formatted
    - [x] Routes are displayed with `inline coding text` (backticks)

## Comments:

---

# Sample State
- [x] State shape is flat!
- [x] State's keys are camelCased
- [x] All keys within the values in the state are accessible in the schema (Ex: if you create a `img_url` key in the state, make sure your database also has a column that contains an `img_url`)
- [x] Correctly formatted
    - [x] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
    - [x] Top level slices
        - [x] `entities`
        - [x] `session`
        - [x] `errors` (here or in `ui`)
        - [x] `ui` (if needed)
    - [x] Should NOT have nested slices, aka  `comments` inside of `posts`
      + Some info from other tables is ok, for instance:
        + the author username and imageurl for a post. basically any info that the user can't change
        + like count and a boolean on whether the user likes the post instead of a likes slice
    
## Comments:

---

# Component Hierarchy with Wireframes

- [x] All routes listed in the routes wiki page is also listed in the component hierarchy
- [x] Each component, if necessary, has route, state, and other components it renders [example](https://github.com/appacademy/bluebird/wiki/component-hierarchy)
- [x] Necessary components are wrapped in a container
- [x] Correctly formatted
    - [x] Bullet point hierarchy
    - [x] Component names are displayed with `inline coding text` (backticks)
- [x] Wireframes included
  - [x] Every component listed in the component hierarchy wiki page has at least one wireframe
  - [x] Every MVPs listed on the MVP wiki page has at least one wireframe
  - [x] Every route listed on the route wiki page has at least one wireframe
  - [x] Contains Containers
  - [x] Contains multiple Index/List
  - [x] Contains multiple IndexItems/ListItems
  - [x] Correctly formatted
    - [x] Wireframe images display on the page
    - [x] Every wireframe has a header title

## Comments:

**Comment by archhere** [comment]
I have to work on my wireframes a bit more.

**Comment by archhere** [comment]
I have made all the changes that we discussed.

**Comment by xnanodax** [comment]
Great work Archana! Thank you for putting in so much time :)!

## Schema
There is one more bullet point left that is related to formatting.

## Component Hierarchy and Wireframes
Consider having a EditBoard/Peg or UpdateBoard/Peg wireframe since that is one of your MVPs!
