### ISSUE TITLE
User Authentication

### ISSUE THREAD

**Issue by archhere** [archhere/peginterest#2]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
  - [x] When errors are displayed, the input boxes should not move
- [x] Smooth, bug free navigation
  - [x] Login errors clears when switching from login form to sign up form (and vice-versa)
  - [ ] Going to a random route `/#/oweiniouewbrviuwebv` should redirect to either `/`, `/login`, or `/signup`
  - [x] Errors should display for both `/signup` and`/login`.
  - [x] Errors should clear when moving between `/signup` and `/login`.
  - [x] Add `cursor: pointer` all your buttons and navlinks!
- [x] Adequate and appropriate seeds
  - [x] Demo Login Works

**Comment by archhere** [comment]
Created user authentication as specified in the specs.

**Comment by xnanodax** [comment]
Great progress!

I unchecked 2 boxes above!

## Additional Comments:
- [ ] At 1150 pixels, the logout button is very far to the right. Meanwhile the user avatar is below the search bar. 

![screen shot 2018-06-11 at 9 21 58 am](https://user-images.githubusercontent.com/20424731/41244110-efd84b28-6d58-11e8-91b1-a3d1154261cb.png)

**Comment by archhere** [comment]
If I keyin some random route, it does bring me back to "/" back if logged in or login page if logged out. But should the url on top change as well?

**Comment by xnanodax** [comment]
I will close the issue for now. There i

# Future Styling Improvements: 
## Functionality 
- [ ] The random route should redirect to any valid page.

## Styling
- [ ] The alignment of the logo is a little off in the Navbar. Also, the name is not center with the center of the avatar picture.
![screen shot 2018-06-15 at 3 33 32 pm](https://user-images.githubusercontent.com/20424731/41492111-c8ca0a38-70b1-11e8-8f2f-f02326fc5bd0.png)
